"""
scripts/define_arm.py

Interactive CLI to scaffold a new custom arm definition.

Usage
─────
    python scripts/define_arm.py

This script will ask you for:
  - Arm name (used as registry key)
  - Number of DOF
  - Joint names and limits
  - Camera names
  - Task description

And generate a ready-to-use Python file you can drop into your project.

You can also pass all args non-interactively:
    python scripts/define_arm.py \\
        --name myrobot \\
        --dof 6 \\
        --joint_names "j1,j2,j3,j4,j5,gripper" \\
        --joint_limits "-3.14,3.14;-1.57,1.57;-2.5,2.5;-1.57,1.57;-3.14,3.14;0,1" \\
        --cameras "top,wrist" \\
        --task "Pick and place the object" \\
        --out_dir customvla/arms/custom
"""

import sys
import argparse
from pathlib import Path


TEMPLATE = '''"""
customvla/arms/custom/{name}.py

Custom arm definition: {class_name}
Generated by scripts/define_arm.py
"""

import numpy as np
from customvla.arms.base import BaseArm
from customvla.arms.registry import register_arm


@register_arm("{name}")
class {class_name}(BaseArm):
    """
    {dof}-DOF arm: {class_name}.

    TODO: Implement send_action() and get_state() for your hardware interface.

    Hardware options:
        - ROS:     publish to a JointState / JointTrajectory topic
        - Serial:  write joint angles to serial port (e.g. Dynamixel)
        - MoveIt:  use MoveGroupCommander.set_joint_value_target()
        - Sim:     call pybullet.setJointMotorControl2() in a loop
        - ur_rtde: rtde_control.moveJ(angles)
    """

    ACTION_DIM  = {dof}
    STATE_DIM   = {dof}

    JOINT_NAMES = {joint_names}

    # Each entry is (min_radians, max_radians).
    # Gripper joints are typically (0.0, 1.0) for fraction-open.
    JOINT_LIMITS = {joint_limits}

    CAMERAS   = {cameras}
    TASK_TEXT = "{task}"

    # ── Optional: set your FPS and image resolution ───────────────────────
    FPS      = 30
    IMG_SIZE = 224

    def __init__(
        self,
        # TODO: add your connection parameters here
        # e.g. robot_ip: str = "192.168.1.100"
        # e.g. ros_topic: str = "/your_arm/joint_commands"
    ):
        # TODO: initialise your hardware connection here
        self._state = np.zeros(self.STATE_DIM, dtype=np.float32)

    # ─────────────────────────────────────────────────────────────────────
    # Required interface (must implement both)
    # ─────────────────────────────────────────────────────────────────────

    def send_action(self, action_vector: np.ndarray) -> None:
        """
        Send joint command to the robot.

        Args:
            action_vector: np.ndarray [ACTION_DIM] in real joint space (radians).
                           Already clipped to JOINT_LIMITS by the RL validator.

        TODO: Replace this stub with your actual hardware call.
        Example (ROS):
            msg = JointState()
            msg.position = action_vector.tolist()
            self._pub.publish(msg)

        Example (ur_rtde):
            self._ctrl.moveJ(action_vector.tolist(), speed=0.5)

        Example (Dynamixel):
            for i, val in enumerate(action_vector):
                self._dxl.set_goal_position(i, val)
        """
        # ── Stub: save internally (no-op) ────────────────────────────────
        self._state = self.clip_to_limits(action_vector)

    def get_state(self) -> np.ndarray:
        """
        Read current joint state from the robot.

        Returns:
            np.ndarray [STATE_DIM] in real joint space (radians).

        TODO: Replace this stub with your actual state read.
        Example (ROS):
            return np.array(self._state_subscriber.data.position)

        Example (ur_rtde):
            return np.array(self._recv.getActualQ())

        Example (Dynamixel):
            return np.array([self._dxl.get_present_position(i)
                             for i in range(self.STATE_DIM)])
        """
        # ── Stub: return last sent state ────────────────────────────────
        return self._state.copy()
'''


def to_class_name(name: str) -> str:
    return "".join(w.capitalize() for w in name.replace("-", "_").split("_")) + "Arm"


def parse_limits(limits_str: str) -> list:
    """Parse 'lo,hi;lo,hi;...' into list of (lo, hi) tuples."""
    result = []
    for pair in limits_str.split(";"):
        lo_s, hi_s = pair.strip().split(",")
        result.append((float(lo_s), float(hi_s)))
    return result


def format_joint_names(names: list) -> str:
    return "[" + ", ".join(f'"{n.strip()}"' for n in names) + "]"


def format_joint_limits(limits: list) -> str:
    rows = [f"    ({lo:.3f}, {hi:.3f})," for lo, hi in limits]
    return "[\n" + "\n".join(rows) + "\n    ]"


def format_cameras(cameras: list) -> str:
    return "[" + ", ".join(f'"{c.strip()}"' for c in cameras) + "]"


def prompt(label: str, default: str = "") -> str:
    suffix = f" [{default}]" if default else ""
    val = input(f"  {label}{suffix}: ").strip()
    return val if val else default


def interactive_mode() -> dict:
    print("\n  ╔══════════════════════════════════════╗")
    print("  ║  CustomVLA — Define New Arm           ║")
    print("  ╚══════════════════════════════════════╝\n")

    name     = prompt("Arm registry name (e.g. 'my_robot', 'franka_2', 'custom6')")
    dof      = int(prompt("Number of DOF (e.g. 6 or 7)", "6"))

    print(f"\n  Enter {dof} joint names (comma-separated):")
    default_names = ",".join(f"joint_{i+1}" for i in range(dof))
    joints_str = prompt("Joint names", default_names)
    joint_names = joints_str.split(",")

    print(f"\n  Enter joint limits as 'lo,hi;lo,hi;...' ({dof} pairs, in radians):")
    print("  Tip: use 0,1 for gripper fraction-open")
    default_limits = ";".join("-3.14,3.14" if i < dof - 1 else "0.0,1.0" for i in range(dof))
    limits_str  = prompt("Joint limits", default_limits)
    joint_limits = parse_limits(limits_str)

    if len(joint_limits) != dof:
        print(f"  ERROR: Expected {dof} limit pairs, got {len(joint_limits)}. Exiting.")
        sys.exit(1)

    print("\n  Enter camera names (comma-separated):")
    cameras_str = prompt("Camera names", "top,wrist")
    cameras = cameras_str.split(",")

    task = prompt("\n  Default task description", "Perform the manipulation task.")

    print(f"\n  Output directory for generated file:")
    out_dir = prompt("Output directory", "customvla/arms/custom")

    return dict(
        name=name, dof=dof, joint_names=joint_names,
        joint_limits=joint_limits, cameras=cameras,
        task=task, out_dir=out_dir,
    )


def generate(params: dict) -> str:
    """Render the arm template from params dict."""
    return TEMPLATE.format(
        name        = params["name"],
        class_name  = to_class_name(params["name"]),
        dof         = params["dof"],
        joint_names = format_joint_names(params["joint_names"]),
        joint_limits = format_joint_limits(params["joint_limits"]),
        cameras     = format_cameras(params["cameras"]),
        task        = params["task"].replace('"', '\\"'),
    )


def main():
    p = argparse.ArgumentParser(description="Scaffold a new CustomVLA arm definition")
    p.add_argument("--name",         default=None, help="Registry key for the arm")
    p.add_argument("--dof",          type=int, default=None)
    p.add_argument("--joint_names",  default=None, help="Comma-separated joint names")
    p.add_argument("--joint_limits", default=None, help="'lo,hi;lo,hi;...' per joint")
    p.add_argument("--cameras",      default=None, help="Comma-separated camera names")
    p.add_argument("--task",         default=None, help="Default task description text")
    p.add_argument("--out_dir",      default="customvla/arms/custom")
    args = p.parse_args()

    if args.name is not None:
        # Non-interactive mode
        if not all([args.dof, args.joint_names, args.joint_limits, args.cameras]):
            p.error("Non-interactive mode requires: --name, --dof, --joint_names, "
                    "--joint_limits, --cameras")
        joint_limits = parse_limits(args.joint_limits)
        params = dict(
            name         = args.name,
            dof          = args.dof,
            joint_names  = args.joint_names.split(","),
            joint_limits = joint_limits,
            cameras      = args.cameras.split(","),
            task         = args.task or "Perform the manipulation task.",
            out_dir      = args.out_dir,
        )
    else:
        params = interactive_mode()

    # Validate
    if len(params["joint_names"]) != params["dof"]:
        print(f"  ERROR: {len(params['joint_names'])} joint names but DOF={params['dof']}")
        sys.exit(1)
    if len(params["joint_limits"]) != params["dof"]:
        print(f"  ERROR: {len(params['joint_limits'])} limit pairs but DOF={params['dof']}")
        sys.exit(1)

    code = generate(params)

    out_dir  = Path(params["out_dir"])
    out_dir.mkdir(parents=True, exist_ok=True)

    # Write __init__.py if missing
    init_file = out_dir / "__init__.py"
    if not init_file.exists():
        init_file.write_text("# Custom arm definitions\n")

    out_file = out_dir / f"{params['name']}.py"
    out_file.write_text(code)

    print(f"\n  ✓ Generated: {out_file}")
    print(f"\n  To register your arm automatically, add this to your training script:")
    print(f"    from {str(out_dir).replace('/', '.')}.{params['name']} import *")
    print(f"\n  Then use it with:")
    print(f"    arm = get_arm('{params['name']}')")
    print(f"    python scripts/train_vla.py --arm {params['name']}")
    print()


if __name__ == "__main__":
    main()
